name: print text file

on:
  push:
    branches:
      - main

jobs:

   print-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print text file
      run: cat hello.txt